#! /usr/bin/env php
<?php

use CraftInstaller\InstallCommand;
use Symfony\Component\Console\Application;

// require __DIR__.'/../../autoload.php';
require 'vendor/autoload.php';

$app = new Application('Craft CMS Installer', '1.0.0');

$app->add(new InstallCommand(new GuzzleHttp\Client));

$app->run();